### ISSUE TITLE
Example to add/remove/update data

### ISSUE THREAD

**Issue by echo66** [wavesjs/ui#13]
Currently, there is no example for that.

**Comment by echo66** [comment]
btw, the way you are managing your references for shapes and datums does not allow to do something like this in the segment layer example:

1) In the second timeline, select a segment.

2) Run the following code: 
```javascript
segmentLayer.data = [ { start: 10, duration: 4, color: 'yellow' } ];
timeline.tracks.render();
timeline.tracks.update();
```

This will cause the following error: *segment-behavior.js:21 Uncaught TypeError: Cannot read property 'x' of undefined*

This happens due to the references that still exist in Layer._behavior.selectedItems

**Comment by b-ma** [comment]
I'm not sure I understand your whole example, but I added your line (which is not a hack IMO) as a removed shape cannot be selected (cf. 54ae76440fbc961030ec7cb44eacd79948ecb6f0).

For the add/remove examples (I think there is many example of updates), It's something I still have to do, but I have to say there is many way of handling this, as it is just a matter of modifying your data Array

**Comment by b-ma** [comment]
I made a State example for the `Breakpoint` layer, which handle adding and removing data from mouse interactions, you can see the code of the `State` here:
https://github.com/wavesjs/ui/blob/develop/es6/states/breakpoint-state.js
The breakpoint example (Advanced Usage part) is showing how to use the `State`. As I told you earlier, I still think there is many way to handle this problem, but this proposal uses the architecture proposed by the library.
