### ISSUE TITLE
Allow "mouseover", "mouseenter" and "mouseout" for segments

### ISSUE THREAD

**Issue by echo66** [wavesjs/ui#16]
According to the current WAVES.UI architecture:
* A Surface instance observes a whole Track instance. There are no Surface instances related to a single Segment instance.
* A BaseBehavior instance is associated to a single layer. There are no BaseBehavior instances related to a single Segment instance.

Using this architecture, there is no way to assign (AFAIK) listeners for "mouseover", "mouseenter", "mouseout" events for each Segment instance in a layer.

**Comment by b-ma** [comment]
Actually, while your description of the architecture is true, you have many ways to listen for these events : 

pure javascript :
```javascript
var $segment  = document.querySelectorAll('.item.segment');
Array.prototype.forEach.call($segments, function($segment) {
    $segment.addEventListener('mouseenter', onMouseEnter, false);
    $segment.addEventListener('mouseleave', onMouseLeave, false);
});
```

if you just need some visual feedback on hover, you can also do that in pure css:
```css
.segment:hover {
    opacity: 0.6 !important;
}
```

I also added `mouseover` and `mouseout` events on the Surface (cf. https://github.com/wavesjs/ui/commit/6982142751608cf125247e0ee9cecc95134eae6e) so you can also do that by listening the timeline now (the segment-layer example is updated too), note that this example, if needed can be easily wrapped into a timeline state to become more generic:
```javascript
timeline.on('event', function(e) {
  var segment;
  var eventType = e.type;

  if (eventType !== 'mouseover' && eventType !== 'mouseout') {
    return;
  }

  segment = segmentLayer.getItemFromDOMElement(e.target);
  if (segment !== null) {
    var datum = segmentLayer.getDatumFromItem(segment);
    datum.opacity = eventType === 'mouseover' ? 1 : 0.8;
    segmentLayer.updateShapes();
  }
});
```

While I agree, the event sytem can still be improved, I insist on the fact that from a layer perspective the mouse or keyboard events do not exists, it's the responsibility of the timelineStates to handle these event and do the work to modify the data or trigger commands on the layer (`select`, `edit`, ...)
