### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by avorio** [wavesjs/ui#17]
Has the documentation moved away from http://wavesjs.github.io/ui/? I'm getting a 404 error.

Many thanks!

**Comment by b-ma** [comment]
Hey,

Thanks for your feedback, I updated the url to the documentation for this version. You can now find it at  http://wavesjs.github.io/ui-deprecated/.
As you can see we will release a new version of the library in few days, so if you start a new project maybe you should check the `develop` branch of the library.

Thanks

**Comment by b-ma** [comment]
Hey again,

Actually I just merged the `develop` branch into `master`. If you use the old version it is now tagged as `0.3.0`. If you'd like to use the new one instead (tagged `1.0.0-alpha`), there is no doc yet (it should come soon) but you can find many examples in the `examples` folder.

**Comment by avorio** [comment]
Thanks @b-ma!

**Comment by b-ma** [comment]
Hey @avorio,

Just to keep you inform that a first version of the documentation for the new API is available at http://wavesjs.github.io/ui

**Comment by avorio** [comment]
The new documentation is fantastic, Benjamin @b-ma! Many thanks for the update.

**Comment by thomasfillon** [comment]
Great !!! Thank you.
