### ISSUE TITLE
Zoomer: split translation  and zoom function

### ISSUE THREAD

**Issue by thomasfillon** [wavesjs/ui#3]
It may be interesting to split the zooming behavior according to the user mouse movement.

Given the mouse movement *delta_x*, *delta_y*:
 1.  if delta_x > delta_y, then only handle translation in the x-axis
 2.  if delta_x < delta_y, then only handle zoom in or zoom out with a proper zoom factor around the anchor point

This should enable to solve #1easilly without side effects
Case 2 could also be handle from mouse wheel event see #2

**Comment by b-ma** [comment]
Done !
see https://github.com/wavesjs/ui/releases/tag/1.0.0-alpha

**Comment by thomasfillon** [comment]
Great !
Merci beaucoup !
