### ISSUE TITLE
Apply correction to documentation

### ISSUE THREAD

**Issue by echo66** [wavesjs/ui#6]
http://wavesjs.github.io/ui/#ui-segment-resizeleft

Rename to resizeRight.

**Comment by echo66** [comment]
Additionaly, there is no explanation for the "marker.setCurrentTime" method that you used in the example. It is kind of intuitive but, in order to maintain a track of all public functions, it should be present in the documentation.

**Comment by b-ma** [comment]
Hey, 

thanks for your feedback, the documentation is updated now
