### ISSUE TITLE
Timeline in "develop" branch

### ISSUE THREAD

**Issue by echo66** [wavesjs/ui#9]
Greetings!

I have compiled the entire "develop" branch and include the resulting code in the web browser. When I try to create a new timeline

```javascript
var T = new wavesUI.timeline();
```

This throw the following error:

TypeError: Cannot read property 'bind' of undefined (edition-state.js:87)

EDIT: 
It happens with every constructor I tried to use. For example:
```javascript
var L = new wavesUI.layer('collection', []);
```

**Comment by b-ma** [comment]
Hey,

We are still in heavy development in the `develop` branch, we are using `browserify` in our development process and have not yet tried to bundle the whole thing, so I can't help you with this error right now.
We should be able to watch more closely on your two issues in 2 or 3 weeks I think. 

(I suspect a problem with the UrlMap, as the `EditionState` file is only 68 lines long...)

Thanks for your feedback !

**Comment by b-ma** [comment]
Hey again,

I compiled the entire library and made a little test (see: `examples/example-boilerplate.html`), I had any of the problem you mentioned, so...

If you want to create a custom build for some reason, you can use the dedicated `npm run bundle`, which transpiles all the file from es6 to es5 and creates the `.umd` and `.min` browserified files (the global exposed in `window` is still `wavesUI` for now)

Let me know if you run any trouble with this build
